### PR TITLE
multiple fixes and enhancements

### LINKED ISSUE #45: error handler for tokens older than 60 mins is needed
as above. will need to be built into the search handler function of results page.

### LINKED ISSUE #46: 'please log in' alert appears 3 times before going away and proceeding with search
this issue is still being investigated.

### LINKED ISSUE #56: Length slider not working on landing page only - works on result page
possibly related to modal

### PR DESCRIPTION
**Pull request by tysau**
-This is a very large change and will be difficult to scan. 
-all tested locally E2E and didn't detect any new errors. It resolves multiple existing errors. 

Summary:
-Fixed log-in loop (alert box was asking logged in users to log in again - they could ignore it but not a good look. 
-removed 'login alert' popup box, replaced with a modal to request log in as needed
-Changed multiple functions to add error catching and handling
-changed authentication flow to detect missing or expired tokens
-added a hidden div which will show a message if user tries an empty search, and will clear itself when user enters text
-refactored some functions and removed some unneccesary code
-re-organised the code and added comments to make it easier to understand
-fixed broken slider on homepage (it was working when implemented, but was broken by a later commit)
-fixed the random button, it now works.
-CSS sheets have been updated with attributes for new additions only. No existing css tags have been modified.

### CODE REVIEW

**Review by ChrisOnions — CHANGES_REQUESTED** [review]
I can't see much wrong  line 210 prevent default needs it's closing brackets

**Comment by tysau** [comment]
> I can't see much wrong line 210 prevent default needs it's closing brackets

updated!

**Comment by neilroy63** [comment]
Great work!

**Review by ChrisOnions — COMMENTED** [review]
Change, fixed looks good

**Pull request merged**
